### PR TITLE
Fix instance data expression

### LINKED ISSUE #9: Region/InstanceID Expression Not Matching
Attempting to spin this up in both a non-ASG managed cluster and one that is resulted in the same error.

```
│ {"level":"warn","time":1610478473,"message":"No config file found"}                                                                                                                                                                                        │
│ {"level":"info","time":1610478473,"message":"Running as server"}                                                                                                                                                                                           │
│ Error: Can't match expression '^/(?P<Region>[a-zA-Z0-9-]+)[a-z]/(?P<InstanceID>[a-zA-Z0-9-]+)$' to 'us-west-2b/i-0af01948154f55129'                                                                                                                        │
│ Usage:                                                                                                                                                                                                                                                     │
│   kubedrainer serve [flags]                                                                                                                                                                                                                                │
│ Flags:                                                                                                                                                                                                                                                     │
│       --cache-dir string               Default HTTP cache directory (default "/.kube/http-cache")                                                                                                                                                          │
│       --certificate-authority string   Path to a cert file for the certificate authority                                                                                                                                                                   │
│       --client-certificate string      Path to a client certificate file for TLS                                                                                                                                                                           │
│       --client-key string              Path to a client key file for TLS                                                                                                                                                                                   │
│       --cluster string                 The name of the kubeconfig cluster to use                                                                                                                                                                           │
│       --context string                 The name of the kubeconfig context to use                                                                                                                                                                           │
│       --delete-local-data              Continue even if there are pods using emptyDir (local data that will be deleted when the node is drained). (default true)                                                                                           │
│       --force                          Continue even if there are pods not managed by a ReplicationController, ReplicaSet, Job, DaemonSet or StatefulSet.                                                                                                  │
│       --grace-period int               Period of time in seconds given to each pod to terminate gracefully. If negative, the default value specified in the pod will be used. (default -1)                                                                 │
│   -h, --help                           help for serve                                                                                                                                                                                                      │
│       --ignore-daemonsets              Ignore DaemonSet-managed pods. (default true)                                                                                                                                                                       │
│       --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure                                                                                                  │
│       --instance-id string             AWS EC2 instance ID to terminate                                                                                                                                                                                    │
│       --kubeconfig string              Path to the kubeconfig file to use for CLI requests.                                                                                                                                                                │
│       --node string                    Kubernetes node name to drain                                                                                                                                                                                       │
│       --pod-selector string            Label selector to filter pods on the node                                                                                                                                                                           │
│       --profile string                 AWS Profile to use                                                                                                                                                                                                  │
│       --region string                  AWS Region to use                                                                                                                                                                                                   │
│       --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")     │
│   -l, --selector string                Selector (label query) to filter on                                                                                                                                                                                 │
│   -s, --server string                  The address and port of the Kubernetes API server                                                                                                                                                                   │
│       --timeout duration               The length of time to wait before giving up, zero means infinite (default 1m0s)                                                                                                                                     │
│       --token string                   Bearer token for authentication to the API server                                                                                                                                                                   │
│       --user string                    The name of the kubeconfig user to use                                                                                                                                                                              │
│ Global Flags:                                                                                                                                                                                                                                              │
│       --config string   config file (default is $HOME/.kubedrainer.yaml)                                                                                                                                                                                   │
│   -d, --debug           sets log level to debug                                                                                                                                                                                                            │
│ {"level":"fatal","time":1610478473,"message":"Can't match expression '^/(?P<Region>[a-zA-Z0-9-]+)[a-z]/(?P<InstanceID>[a-zA-Z0-9-]+)$' to 'us-west-2b/i-0af01948154f55129'"}
```

Looks like this just needs a backslash in the expression with the starting slash removed?
https://github.com/VirtusLab/kubedrainer/blob/9a7d7d7e92ec9bcd6c0a3db75e05d8ef2ae7a76f/cmd/kubedrainer/serve.go#L204
`^(?P<Region>[a-zA-Z0-9-]+)[a-z]\/(?P<InstanceID>[a-zA-Z0-9-]+)$`

### PR DESCRIPTION
**Pull request by tgraskemper**
Fixes: https://github.com/VirtusLab/kubedrainer/issues/9

```
│ {"level":"warn","time":1610568409,"message":"No config file found"}                                                                                                                                                                                        │
│ {"level":"info","time":1610568409,"message":"Running as server"}                                                                                                                                                                                           │
│ {"level":"debug","time":1610568409,"message":"All keys: [timeout region force instance-id ignore-daemonsets help user request-timeout certificate-authority pod-selector server cache-dir client-certificate debug context client-key cluster delete-local │
│ {"level":"debug","time":1610568409,"message":"All settings: map[cache-dir:/.kube/http-cache certificate-authority: client-certificate: client-key: cluster: config: context: debug:true delete-local-data:true force:false grace-period:-1 help:false igno │
│ {"level":"debug","time":1610568409,"message":"'cache-dir' -> flag: '/.kube/http-cache' | setting: '/.kube/http-cache'"}                                                                                                                                    │
│ {"level":"debug","time":1610568409,"message":"'certificate-authority' -> flag: '' | setting: ''"}                                                                                                                                                          │
│ {"level":"debug","time":1610568409,"message":"'client-certificate' -> flag: '' | setting: ''"}                                                                                                                                                             │
│ {"level":"debug","time":1610568409,"message":"'client-key' -> flag: '' | setting: ''"}                                                                                                                                                                     │
│ {"level":"debug","time":1610568409,"message":"'cluster' -> flag: '' | setting: ''"}                                                                                                                                                                        │
│ {"level":"debug","time":1610568409,"message":"'config' -> flag: '' | setting: ''"}                                                                                                                                                                         │
│ {"level":"debug","time":1610568409,"message":"'context' -> flag: '' | setting: ''"}                                                                                                                                                                        │
│ {"level":"debug","time":1610568409,"message":"'debug' -> flag: 'true' | setting: 'true'"}                                                                                                                                                                  │
│ {"level":"debug","time":1610568409,"message":"'delete-local-data' -> flag: 'true' | setting: 'true'"}                                                                                                                                                      │
│ {"level":"debug","time":1610568409,"message":"'force' -> flag: 'false' | setting: 'false'"}                                                                                                                                                                │
│ {"level":"debug","time":1610568409,"message":"'grace-period' -> flag: '-1' | setting: '-1'"}                                                                                                                                                               │
│ {"level":"debug","time":1610568409,"message":"'help' -> flag: 'false' | setting: 'false'"}                                                                                                                                                                 │
│ {"level":"debug","time":1610568409,"message":"'ignore-daemonsets' -> flag: 'true' | setting: 'true'"}                                                                                                                                                      │
│ {"level":"debug","time":1610568409,"message":"'insecure-skip-tls-verify' -> flag: 'false' | setting: 'false'"}                                                                                                                                             │
│ {"level":"debug","time":1610568409,"message":"'instance-id' -> flag: '' | setting: ''"}                                                                                                                                                                    │
│ {"level":"debug","time":1610568409,"message":"'kubeconfig' -> flag: '' | setting: ''"}                                                                                                                                                                     │
│ {"level":"debug","time":1610568409,"message":"'node' -> flag: '' | setting: 'ip-172-30-0-111.us-west-2.compute.internal'"}                                                                                                                                 │
│ {"level":"debug","time":1610568409,"message":"'pod-selector' -> flag: '' | setting: ''"}                                                                                                                                                                   │
│ {"level":"debug","time":1610568409,"message":"'profile' -> flag: '' | setting: ''"}                                                                                                                                                                        │
│ {"level":"debug","time":1610568409,"message":"'region' -> flag: '' | setting: ''"}                                                                                                                                                                         │
│ {"level":"debug","time":1610568409,"message":"'request-timeout' -> flag: '0' | setting: '0'"}                                                                                                                                                              │
│ {"level":"debug","time":1610568409,"message":"'selector' -> flag: '' | setting: ''"}                                                                                                                                                                       │
│ {"level":"debug","time":1610568409,"message":"'server' -> flag: '' | setting: ''"}                                                                                                                                                                         │
│ {"level":"debug","time":1610568409,"message":"'timeout' -> flag: '1m0s' | setting: '1m0s'"}                                                                                                                                                                │
│ {"level":"debug","time":1610568409,"message":"'token' -> flag: '' | setting: ''"}                                                                                                                                                                          │
│ {"level":"debug","time":1610568409,"message":"'user' -> flag: '' | setting: ''"}                                                                                                                                                                           │
│ {"level":"debug","time":1610568409,"message":"Settings: {Kubernetes:{ConfigFlags:{CacheDir:/.kube/http-cache KubeConfig: ClusterName: AuthInfoName: Context: Namespace:<nil> APIServer: Insecure:false CertFile: KeyFile: CAFile: BearerToken: Impersonate │
│ {"level":"debug","time":1610568409,"message":"Context: "}                                                                                                                                                                                                  │
│ {"level":"debug","time":1610568409,"message":"Configured Host: https://172.28.252.1:443"}                                                                                                                                                                  │
│ {"level":"debug","time":1610568409,"message":"Configured AuthProvider: <nil>"}                                                                                                                                                                             │
│ {"level":"debug","time":1610568409,"message":"Configured ExecProvider: <nil>"}                                                                                                                                                                             │
│ {"level":"debug","time":1610568410,"message":"Server version: v1.18.8"}                                                                                                                                                                                    │
│ {"level":"debug","time":1610568410,"message":"Getting node information"}                                                                                                                                                                                   │
│ {"level":"debug","time":1610568410,"message":"Using default AWS API credentials profile"}                                                                                                                                                                  │
│ {"level":"info","time":1610568410,"message":"Running node drainer on node 'ip-172-30-0-111.us-west-2.compute.internal' on instance 'i-001d9c66ac115fed9' in region 'us-west-2' and profile 'default'"}                                                     │
│ {"level":"info","time":1610568410,"message":"Sleeping 10s seconds"}                                                                                                                                                                                        │
```

### CODE REVIEW

**Comment by tgraskemper** [comment]
@pawelprazak Would you be able to take a look at this soon?

File: cmd/kubedrainer/serve.go [hunk 1]
```diff
@@ -201,7 +201,7 @@ func GetNodeInformation(nodeName string, kubernetesClient k8s.Interface) (string
 	}
 	switch providerName {
 	case "aws":
-		awsNodeIDExpression := `^/(?P<Region>[a-zA-Z0-9-]+)[a-z]/(?P<InstanceID>[a-zA-Z0-9-]+)$`
+		awsNodeIDExpression := `^(?P<Region>[a-zA-Z0-9-]+)[a-z]\/(?P<InstanceID>[a-zA-Z0-9-]+)$`
```
Comment (pawelprazak) [inline cmd/kubedrainer/serve.go]: This will break backwards compatibility, but making the first `/` optional should make it work for both cases:
`^/?(?P<Region>[a-zA-Z0-9-]+)[a-z]/(?P<InstanceID>[a-zA-Z0-9-]+)$`

File: go.mod [hunk 2]
```diff
@@ -15,6 +15,7 @@ require (
 	github.com/spf13/pflag v1.0.5
 	github.com/spf13/viper v1.7.1
 	github.com/stretchr/testify v1.6.1 // indirect
+	golang.org/x/net v0.0.0-20201021035429-f5854403a974 // indirect
```
Comment (pawelprazak) [inline go.mod]: plese do not include automatic changes to `go.mod` and `go.sum` since I'll do it anyway while releasing.

**Review by pawelprazak — CHANGES_REQUESTED** [review]
Thank you for your contribution, please have a look the comments.

File: go.mod (hunk 2 above)
Comment (tgraskemper) [reply go.mod]: Thanks, will update.

File: cmd/kubedrainer/serve.go (hunk 1 above)
Comment (tgraskemper) [reply cmd/kubedrainer/serve.go]: Thanks for catching this.  I updated this as I had been checking with the wrong language.

**Comment by tgraskemper** [comment]
Something I'd like to ask about as I was looking through this.  I was expecting that a failure of pulling instanceId and region would have resulted in the fallback of pulling from the instance metadata, but the logic in the code always returns an error that forces an exit of the application.  Am I misunderstanding the purpose of this?

https://github.com/VirtusLab/kubedrainer/blob/master/cmd/kubedrainer/serve.go#L83-L123

**Comment by pawelprazak** [comment]
I think the intent was to try get the info from various sources but fail in case of an error, but it has been a while so the original intent is vague at this point ;)
